// <auto-generated />
using System;
using ComponentProcessingMicroservice.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComponentProcessingMicroservice.Migrations
{
    [DbContext(typeof(ComponentProcessingDbContext))]
    partial class ComponentProcessingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ComponentProcessingMicroservice.Database.Entities.CreditCard", b =>
                {
                    b.Property<int>("CreditCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CreditCardLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreditCardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("CreditCardId");

                    b.ToTable("CreditCards");
                });

            modelBuilder.Entity("ComponentProcessingMicroservice.Database.Entities.DefectiveComponent", b =>
                {
                    b.Property<int>("DefectiveComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("DefectiveComponentId");

                    b.ToTable("DefectiveComponents");
                });

            modelBuilder.Entity("ComponentProcessingMicroservice.Database.Entities.ProcessRequest", b =>
                {
                    b.Property<int>("ProcessRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditCardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DefectiveComponentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPriority")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProcessRequestId");

                    b.HasIndex("DefectiveComponentId");

                    b.ToTable("ProcessRequests");
                });

            modelBuilder.Entity("ComponentProcessingMicroservice.Database.Entities.ProcessResponse", b =>
                {
                    b.Property<int>("ProcessResponsetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfDelivery")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PackageAndDeliveryCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProcessRequestId")
                        .HasColumnType("int");

                    b.Property<decimal>("ProcessingCharge")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProcessResponsetId");

                    b.HasIndex("ProcessRequestId");

                    b.ToTable("ProcessResponses");
                });

            modelBuilder.Entity("ComponentProcessingMicroservice.Database.Entities.ProcessRequest", b =>
                {
                    b.HasOne("ComponentProcessingMicroservice.Database.Entities.DefectiveComponent", "DefectiveComponent")
                        .WithMany()
                        .HasForeignKey("DefectiveComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComponentProcessingMicroservice.Database.Entities.ProcessResponse", b =>
                {
                    b.HasOne("ComponentProcessingMicroservice.Database.Entities.ProcessRequest", "processRequest")
                        .WithMany()
                        .HasForeignKey("ProcessRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
